// auto generated by go tool dist

package sys

const DefaultGoroot = `/home/yanni/biscuit/golang1.7`
const TheVersion = `devel +c1746ed Thu Jan 5 21:15:51 2017 -0500`
const Goexperiment = ``
const StackGuardMultiplier = 1

